name: Unzip ZIP file

on:
  push:
    branches:
      - main

jobs:
  unzip_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: List files before unzip
        run: ls -la zips

      - name: Unzip ZIP file
        run: unzip "zips/All Commands-20250719T092014Z-1-001.zip" -d extracted

      - name: List files after unzip
        run: ls -la extracted
