name: Unzip ZIP file on push

on:
  push:
    branches:
      - main

jobs:
  unzip_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Show files inside zips folder
        run: ls -la zips

      - name: Unzip the ZIP file
        run: unzip "zips/All Commands-20250719T092014Z-1-001.zip" -d extracted

      - name: Show files inside extracted folder
        run: ls -la extracted
